version: '3'
services:
    dev-web:
        build:
            context: ./app-web
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        ports:
            - "8080:8080"
        env_file:
            - ./app-web/.env.development
        volumes:
            - ./app-web:/app

    prod-web:
        build:
            context: ./app-web
            dockerfile: Dockerfile.prod
            args:
                - NODE_ENV=production
        ports:
            - "3001:3000"
        env_file:
            - ./app-web/.env.production
    api-dev:
        build:
            context: ./app-server
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        ports:
            - "4200:4200"
        env_file:
            - ./app-server/.env.development
        volumes:
            - ./app-server:/app
    api-prod:
        build:
            context: ./app-server
            dockerfile: Dockerfile.prod
            args:
                - NODE_ENV=production
        ports:
            - "3333:3333"
        env_file:
            - ./app-server/.env.production
