version: '3'
services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NODE_ENV=development
        ports:
            - "3000:3000"
        env_file:
            - .env.development
        volumes:
            - .:/app

    prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                - NODE_ENV=production
        ports:
            - "3001:3000"
        env_file:
            - .env.production
