# Build stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --silent
COPY . ./
RUN npm run build

RUN npm prune --production

#Run stage
FROM node:20-alpine AS stage
WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

COPY package.json .

ENV NODE_ENV=production

EXPOSE 3333

CMD ["node", "dist/server.js"]